//! Generic parser fuzzing: prove that a parser never panics on arbitrary
//! bytes, and surfaces every panic as a clear assertion failure.

use std::panic::{catch_unwind, AssertUnwindSafe};

/// Assert that invoking `parser` on `input` never panics.
///
/// Designed to be called from inside a `proptest!` block where the input bytes
/// are generated by the harness:
///
/// ```rust
/// use tpt_av_test_fuzz::fuzz_parser_never_panics;
///
/// // toy parser: panics only if the buffer starts with b"PANIC!"
/// fn toy(data: &[u8]) -> Result<(), ()> {
///     if data.starts_with(b"PANIC!") {
///         panic!("toy parser bug")
///     }
///     Ok(())
/// }
///
/// proptest::proptest! {
///     #![proptest_config(proptest::prelude::ProptestConfig::with_cases(8))]
///     fn toy_never_panics(data in proptest::collection::vec(proptest::prelude::any::<u8>(), 0..64)) {
///         fuzz_parser_never_panics!(parser: toy, input: &data);
///     }
/// }
/// ```
///
/// The body is wrapped in `catch_unwind`, so a panic in the parser becomes an
/// assertion failure instead of aborting the whole test binary; only the
/// failing case is reported.
#[macro_export]
macro_rules! fuzz_parser_never_panics {
    (parser: $parser:path, input: $input:expr $(,)?) => {{
        let outcome = $crate::parser::panics_on(|| $parser($input));
        assert!(
            !outcome,
            "tpt-av-test: parser `{}` panicked on fuzzed input; input was \
             generated deterministically — see `tpt_av_test_fuzz::seed` to \
             reproduce",
            stringify!($parser),
        );
    }};
}

/// Returns `true` if `f` panics, otherwise `false`.
pub fn panics_on<F, R>(f: F) -> bool
where
    F: FnOnce() -> R,
{
    catch_unwind(AssertUnwindSafe(f)).is_err()
}
